# /roles/k3s_worker/tasks/main.yaml
---
- name: Download k3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/install_k3s.sh
    mode: '0755'

- name: Check if k3s is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/k3s
  register: k3s_installed

- name: Install k3s agent (only if not installed)
  ansible.builtin.shell: |
    /tmp/install_k3s.sh agent \
      {{ extra_agent_args }} \
      --token={{ k3s_token }} \
      --server https://{{ apiserver_endpoint }}:6443
  environment:
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
  when: not k3s_installed.stat.exists
  no_log: true  # avoids token leakage in logs
