---
k3s_version: v1.30.2+k3s2
ansible_user: vagrant

# interface which will be used for flannel
flannel_iface: eth1 # (vagrant uses eth1)

# enable kube-vip ARP broadcasts
kube_vip_arp: true

# apiserver_endpoint is virtual ip-address which will be configured on each master
apiserver_endpoint: 192.168.10.222

# k3s_token is required  masters can talk together securely
# this token should be alpha numeric only
k3s_token: some-secret-password

# change these to your liking, the only required are: --disable servicelb, --tls-san {{ apiserver_endpoint }}
extra_server_args: >-
  --tls-san {{ apiserver_endpoint }}
  --disable servicelb
  --disable traefik
  --write-kubeconfig-mode 644
  --flannel-iface={{ flannel_iface }}

server_init_args: >-
  {% if groups['master'] | length > 1 %}
    {% if inventory_hostname == groups['master'][0] %}
      --cluster-init
    {% else %}
      --server https://{{ master_ip | default('') }}:6443
    {% endif %}
    --token {{ k3s_token }}
  {% endif %}
  {{ extra_server_args }}

# image tag for kube-vip
kube_vip_tag_version: v0.8.2
# metallb type frr or native
metal_lb_type: native
# metallb mode layer2 or bgp
metal_lb_mode: layer2

# image tag for metal lb
metal_lb_speaker_tag_version: v0.14.8
metal_lb_controller_tag_version: v0.14.8

# metallb ip range for load balancer
metal_lb_ip_range: 192.168.10.191-192.168.10.199
