---
- hosts: k3s_cluster:children
  become: true
  roles:
    - role: common
    - role: downloads

- hosts: master
  become: true
  roles:
    - role: k3s_master
    - role: post_master

- hosts: node
  become: true
  roles:
    - role: k3s_worker
