---
- name: Install k9s (use RPM on Rocky 9)
  ansible.builtin.shell: |
    wget https://github.com/derailed/k9s/releases/download/v0.32.7/k9s_Linux_amd64.rpm
    dnf install -y ./k9s_Linux_amd64.rpm
    rm k9s_Linux_amd64.rpm
  when: ansible_facts['os_family'] == 'RedHat'
