---

- name: Deploy K3s
  ansible.builtin.include_tasks: k3s_server.yaml

# deploy oncly on first master
- name: Deploy vip manifest
  ansible.builtin.include_tasks:
    file: kube_vip.yaml
    apply:
      tags: [kube_vip]
  tags: [kube_vip]
  when:
    - install_kube_vip | bool
    - inventory_hostname == groups['master'][0]

- name: Deploy metallb manifest
  ansible.builtin.include_tasks:
    file: metallb.yaml
    apply:
      tags: [metallb]
  tags: [metallb]
  when:
    - install_metallb | bool
    - inventory_hostname == groups['master'][0]

# deploy once on first master
- name: Install k9s
  ansible.builtin.include_tasks:
    file: k9s_install.yaml
    apply:
      tags: [k9s]
  tags: [k9s]
  when:
    - install_k9s | bool
    - inventory_hostname == groups['master'][0]
#
