---

- name: Deploy K3s
  ansible.builtin.include_tasks: k3s_server.yaml

- name: Deploy vip manifest
  ansible.builtin.include_tasks: kube_vip.yaml

- name: Deploy metallb manifest
  ansible.builtin.include_tasks: metallb.yaml
  tags: metallb

- name: Install k9s
  ansible.builtin.include_tasks: k9s_install.yaml
  tags: k9s
