---
ansible_user: ansible


#################################
# K3s
#################################

k3s_server_location: /var/lib/rancher/k3s
k3s_binary_path: /usr/local/bin/k3s

k3s_version: v1.30.2+k3s2
# k3s_token is required  masters can talk together securely
# this token should be alpha numeric only
k3s_token: some-secret-password

# change these to your liking, the only required are: --disable servicelb, --tls-san {{ apiserver_endpoint }}
extra_server_args: >-
  --tls-san {{ apiserver_endpoint }}
  --disable servicelb
  --disable traefik
  --write-kubeconfig-mode 644
  --flannel-iface={{ flannel_iface }}
  --token={{ k3s_token }}

# interface which will be used for flannel
flannel_iface: eth1 # (vagrant uses eth1)

#################################
# kube-vip
#################################

# enable kube-vip ARP broadcasts
kube_vip_arp: true
kube_vip_interface: ens5

# apiserver_endpoint is virtual ip-address which will be configured on each master
apiserver_endpoint: 192.168.10.222


# image tag for kube-vip
kube_vip_tag_version: v0.8.2


#################################
# MetalLB
#################################

# metallb type frr or native
metal_lb_type: native
# metallb mode layer2 or bgp
metal_lb_mode: layer2

# image tag for metal lb
metal_lb_tag_version: v0.14.8

# metallb ip range for load balancer
metal_lb_ip_range: 192.168.10.191-192.168.10.199
