k3s_token: some-secret-password

# Interface for flannel on the agent. Falls back to eth1 (vagrant default) unless
# flannel_iface is set via group_vars/inventory.
flannel_iface: eth1

extra_agent_args: >-
  --flannel-iface={{ flannel_iface }}
