name: Kubeconfig-Sync Integration Test

on:
  push:
    paths:
      - 'Makefile'
      - 'scripts/ci/remote-vm.sh'
      - 'scripts/kubeconfig_sync.sh'
  pull_request:
    paths:
      - 'Makefile'
      - 'scripts/ci/remote-vm.sh'
      - 'scripts/kubeconfig_sync.sh'

jobs:
  sync-test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        ports:
          - 2375:2375
        options: >-
          --privileged
          --network host
          --cap-add ALL
          --security-opt seccomp=unconfined
        env:
          DOCKER_HOST: tcp://localhost:2375

    env:
      SSH_HOST: localhost
      SSH_PORT: 2222
      SSH_USER: root
      SSH_KEY_FILE: ${{ runner.workspace }}/id_rsa

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate SSH keypair
        run: |
          ssh-keygen -t rsa -b 2048 -f id_rsa -N ""
          chmod 600 id_rsa

      - name: Provision remote VM & Kind cluster
        run: scripts/ci/remote-vm.sh
        shell: bash

      - name: Run kubeconfig-sync
        run: make kubeconfig-sync

      - name: List merged contexts
        run: |
          echo "📝 contexts in ~/.kube/config:"
          kubectl config get-contexts -o name

      - name: Switch to remote context
        run: |
          kubectl config use-context kind-ci-test

      - name: Verify remote cluster nodes
        run: kubectl get nodes
